# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T14:44:19+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class BadRequestResponse(BaseModel):
    detail: Optional[Union[str, Dict[str, Any]]] = Field(
        None,
        description='Contains parameter or domain specific information related to the error and why it occurred.',
    )
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)',
        examples=['Bad Request'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Invalid Params'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#requestvalidationerror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[400]
    )
    type_name: Optional[str] = Field(
        None,
        description='The type of error returned',
        examples=['RequestValidationError'],
    )


class CreatedAt(RootModel[datetime]):
    root: datetime = Field(
        ...,
        description='The date and time when the object was created.',
        examples=['2020-09-30T07:43:32.000Z'],
        title='Created at (timestamp)',
    )


class CreatedBy(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='The user who created the object.',
        examples=['12345'],
        title='Created by',
    )


class Description(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='A description of the object.',
        examples=['A description'],
        title='Description',
    )


class DownstreamId(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='The third-party API ID of original entity',
        examples=['12345'],
    )


class DriveGroupsFilter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    parent_group_id: Optional[str] = Field(
        None, description='ID of the drive group to filter on', examples=['1234']
    )


class DrivesFilter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    group_id: Optional[str] = Field(
        None, description='ID of the drive group to filter on', examples=['1234']
    )


class ExpiresAt(RootModel[datetime]):
    root: datetime = Field(..., examples=['2022-09-30T07:43:32.000Z'])


class FileSize(RootModel[int]):
    root: int = Field(
        ..., description='The size of the file in bytes', examples=[1810673]
    )


class FileStorageEventType(Enum):
    field_ = '*'
    file_storage_file_created = 'file-storage.file.created'
    file_storage_file_updated = 'file-storage.file.updated'
    file_storage_file_deleted = 'file-storage.file.deleted'


class FileType(Enum):
    file = 'file'
    folder = 'folder'
    url = 'url'


class FilesFilter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    drive_id: Optional[str] = Field(
        None, description='ID of the drive to filter on', examples=['1234']
    )
    folder_id: Optional[str] = Field(
        None,
        description='ID of the folder to filter on. The root folder has an alias "root"',
        examples=['root'],
    )
    shared: Optional[bool] = Field(
        None, description='Only return files and folders that are shared'
    )


class FilesSearch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    drive_id: Optional[str] = Field(
        None, description='ID of the drive to filter on', examples=['1234']
    )
    query: str = Field(
        ...,
        description='The query to search for. May match across multiple fields.',
        examples=['logo jpg'],
    )


class By(Enum):
    updated_at = 'updated_at'
    name = 'name'


class Id(RootModel[str]):
    root: str = Field(
        ...,
        description='A unique identifier for an object.',
        examples=['12345'],
        title='ID',
    )


class LinkedFolder(BaseModel):
    id: Id
    name: Optional[str] = Field(
        None, description='The name of the folder', examples=['Personal']
    )


class Links(BaseModel):
    current: Optional[str] = Field(
        None,
        description='Link to navigate to the current page through the API',
        examples=['https://unify.apideck.com/crm/companies'],
    )
    next: Optional[str] = Field(
        None,
        description='Link to navigate to the previous page through the API',
        examples=[
            'https://unify.apideck.com/crm/companies?cursor=em9oby1jcm06OnBhZ2U6OjM'
        ],
    )
    previous: Optional[str] = Field(
        None,
        description='Link to navigate to the previous page through the API',
        examples=[
            'https://unify.apideck.com/crm/companies?cursor=em9oby1jcm06OnBhZ2U6OjE%3D'
        ],
    )


class Cursors(BaseModel):
    current: Optional[str] = Field(
        None,
        description='Cursor to navigate to the current page of results through the API',
        examples=['em9oby1jcm06OnBhZ2U6OjI='],
    )
    next: Optional[str] = Field(
        None,
        description='Cursor to navigate to the next page of results through the API',
        examples=['em9oby1jcm06OnBhZ2U6OjM='],
    )
    previous: Optional[str] = Field(
        None,
        description='Cursor to navigate to the previous page of results through the API',
        examples=['em9oby1jcm06OnBhZ2U6OjE='],
    )


class Meta(BaseModel):
    cursors: Optional[Cursors] = Field(
        None,
        description='Cursors to navigate to previous or next pages through the API',
    )
    items_on_page: Optional[int] = Field(
        None,
        description='Number of items returned in the data property of the response',
        examples=[50],
    )


class NotFoundResponse(BaseModel):
    detail: Optional[Union[str, Dict[str, Any]]] = Field(
        None,
        description='Contains parameter or domain specific information related to the error and why it occurred.',
    )
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)',
        examples=['Not Found'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Unknown Widget'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#entitynotfounderror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[404]
    )
    type_name: Optional[str] = Field(
        None, description='The type of error returned', examples=['EntityNotFoundError']
    )


class NotImplementedResponse(BaseModel):
    detail: Optional[Union[str, Dict[str, Any]]] = Field(
        None,
        description='Contains parameter or domain specific information related to the error and why it occurred.',
    )
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)',
        examples=['Not Implemented'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Unmapped Attribute'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#mappingerror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[501]
    )
    type_name: Optional[str] = Field(
        None, description='The type of error returned', examples=['MappingError']
    )


class Owner(BaseModel):
    email: Optional[str] = Field(
        None, description='Email of the owner', examples=['hello@apideck.com']
    )
    id: Optional[str] = Field(None, description='ID of the owner', examples=['12345'])
    name: Optional[str] = Field(
        None, description='Name of the owner', examples=['Elon Musk']
    )


class ParentFolderId(RootModel[str]):
    root: str = Field(
        ...,
        description='The parent folder to create the new file within.',
        examples=['1234'],
    )


class PassThroughQuery(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    example_downstream_property: Optional[str] = Field(
        None,
        description='All passthrough query parameters are passed along to the connector as is (?pass_through[search]=leads becomes ?search=leads)',
    )


class PaymentRequiredResponse(BaseModel):
    detail: Optional[str] = Field(
        None,
        description='Contains parameter or domain specific information related to the error and why it occurred.',
        examples=['You have reached your limit of 2000'],
    )
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)',
        examples=['Payment Required'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Request Limit Reached'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#requestlimiterror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[402]
    )
    type_name: Optional[str] = Field(
        None, description='The type of error returned', examples=['RequestLimitError']
    )


class Scope(Enum):
    public = 'public'
    company = 'company'


class SharedLinkTarget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    name: Optional[str] = Field(
        None, description='The name of the file', examples=['sample.jpg']
    )
    type: Optional[FileType] = None


class SortDirection(Enum):
    asc = 'asc'
    desc = 'desc'


class Detail(BaseModel):
    context: Optional[str] = None
    error: Optional[Dict[str, Any]] = None


class TooManyRequestsResponse(BaseModel):
    detail: Optional[Detail] = None
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 6585)',
        examples=['Too Many Requests'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Connector Rate Limit Error'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#connectorratelimiterror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[429]
    )
    type_name: Optional[str] = Field(
        None,
        description='The type of error returned',
        examples=['ConnectorRateLimitError'],
    )


class UnauthorizedResponse(BaseModel):
    detail: Optional[str] = Field(
        None,
        description='Contains parameter or domain specific information related to the error and why it occurred.',
        examples=[
            'Failed to generate valid JWT Session. Verify applicationId is correct'
        ],
    )
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)',
        examples=['Unauthorized'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Unauthorized Request'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#unauthorizederror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[401]
    )
    type_name: Optional[str] = Field(
        None, description='The type of error returned', examples=['UnauthorizedError']
    )


class UnexpectedErrorResponse(BaseModel):
    detail: Optional[Union[str, Dict[str, Any]]] = Field(
        None,
        description='Contains parameter or domain specific information related to the error and why it occurred.',
    )
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)',
        examples=['Bad Request'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Invalid Params'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#unauthorizederror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[400]
    )
    type_name: Optional[str] = Field(
        None,
        description='The type of error returned',
        examples=['RequestHeadersValidationError'],
    )


class UnifiedId(BaseModel):
    id: str = Field(
        ...,
        description='The unique identifier of the resource',
        examples=['12345'],
        title='Id',
    )


class UnprocessableResponse(BaseModel):
    detail: Optional[str] = Field(
        None,
        description='Contains parameter or domain specific information related to the error and why it occurred.',
        examples=[
            'Unprocessable request, please verify your request headers and body.'
        ],
    )
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)',
        examples=['Unprocessable Entity'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Invalid State'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#invalidstateerror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[422]
    )
    type_name: Optional[str] = Field(
        None, description='The type of error returned', examples=['InvalidStateError']
    )


class UpdateDriveGroupResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['update'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['DriveGroups']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class UpdateDriveResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['update'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Drives']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class UpdateFileRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Optional[str] = Field(
        None,
        description='Optional description of the file.',
        examples=['Renamed PDF Document'],
    )
    name: Optional[str] = Field(
        None, description='The name of the file.', examples=['New Name.pdf']
    )
    parent_folder_id: Optional[ParentFolderId] = None


class UpdateFileResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['update'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['files']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class UpdateFolderRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Optional[str] = Field(
        None,
        description='Optional description of the folder.',
        examples=['My Personal Documents'],
    )
    id: Optional[Id] = None
    name: Optional[str] = Field(
        None, description='The name of the folder.', examples=['Documents']
    )
    parent_folder_id: Optional[ParentFolderId] = None


class UpdateFolderResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['update'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Folders']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['undefined']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class UpdateSharedLinkResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['update'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Shared Links']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['dropbox']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class UpdateUploadSessionResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['one'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['UploadSessions']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['dropbox']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class UpdatedAt(RootModel[Optional[datetime]]):
    root: Optional[datetime] = Field(
        None,
        description='The date and time when the object was last updated.',
        examples=['2020-09-30T07:43:32.000Z'],
        title='Updated at (timestamp)',
    )


class UpdatedBy(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='The user who last updated the object.',
        examples=['12345'],
        title='Updated by',
    )


class UploadSession(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_at: Optional[ExpiresAt] = None
    id: Optional[Id] = None
    parallel_upload_supported: Optional[bool] = Field(
        None,
        description='Indicates if parts of the file can uploaded in parallel.',
        examples=[True],
    )
    part_size: Optional[float] = Field(
        None,
        description='Size in bytes of each part of the file that you will upload. Uploaded parts need to be this size for the upload to be successful.',
        examples=[1000000],
    )
    success: Optional[bool] = Field(
        None,
        description='Indicates if the upload session was completed successfully.',
        examples=[True],
    )
    uploaded_byte_range: Optional[str] = Field(
        None,
        description='The range of bytes that was successfully uploaded.',
        examples=['0-42'],
    )


class WebhookEvent(BaseModel):
    entity_id: Optional[str] = Field(
        None,
        description="The service provider's ID of the entity that triggered this event",
        examples=['123456ASDF'],
    )
    entity_type: Optional[str] = Field(
        None,
        description='The type entity that triggered this event',
        examples=['Company'],
    )
    entity_url: Optional[str] = Field(
        None,
        description='The url to retrieve entity detail.',
        examples=['https://unify.apideck.com/crm/contacts/123456'],
    )
    event_id: Optional[str] = Field(
        None,
        description='Unique reference to this request event',
        examples=['9755c355-56c3-4a2f-a2da-86ff4411fccb'],
    )
    execution_attempt: Optional[float] = Field(
        None,
        description='The current count this request event has been attempted',
        examples=[2],
    )
    occurred_at: Optional[str] = Field(
        None,
        description='ISO Datetime for when the original event occurred',
        examples=['2021-10-01T03:14:55.419Z'],
    )
    service_id: Optional[str] = Field(
        None, description='Service provider identifier', examples=['close']
    )
    event_type: Optional[FileStorageEventType] = None


class FileStorageUploadSessionsIdFinishPostRequest(BaseModel):
    pass
    model_config = ConfigDict(
        extra='forbid',
    )


class CopyFolderRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[Id] = None
    name: Optional[str] = Field(
        None, description='The name of the folder.', examples=['Documents']
    )
    parent_folder_id: ParentFolderId


class CreateDriveGroupResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['add'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['DriveGroups']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class CreateDriveResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['add'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Drives']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class CreateFileRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Optional[str] = Field(
        None,
        description='Optional description of the file.',
        examples=['My Personal Documents'],
    )
    drive_id: Optional[str] = Field(
        None, description='ID of the drive to upload to.', examples=['1234']
    )
    name: str = Field(..., description='The name of the file.', examples=['Documents'])
    parent_folder_id: ParentFolderId


class CreateFileResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['add'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['files']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class CreateFolderRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Optional[str] = Field(
        None,
        description='Optional description of the folder.',
        examples=['My Personal Documents'],
    )
    drive_id: Optional[str] = Field(
        None, description='ID of the drive to create the folder in.', examples=['1234']
    )
    id: Optional[Id] = None
    name: str = Field(
        ..., description='The name of the folder.', examples=['Documents']
    )
    parent_folder_id: ParentFolderId


class CreateFolderResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['add'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Folders']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['undefined']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class CreateSharedLinkResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['add'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Shared Links']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['dropbox']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class CreateUploadSessionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    drive_id: Optional[str] = Field(
        None, description='ID of the drive to upload to.', examples=['1234']
    )
    name: str = Field(..., description='The name of the file.', examples=['Documents'])
    parent_folder_id: ParentFolderId
    size: FileSize


class CreateUploadSessionResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['one'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['UploadSessions']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['dropbox']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class DeleteDriveGroupResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['delete'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['DriveGroups']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class DeleteDriveResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['delete'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Drives']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class DeleteFileResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['delete'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['files']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class DeleteFolderResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['delete'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Folders']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['undefined']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class DeleteSharedLinkResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['delete'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Shared Links']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['dropbox']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class DeleteUploadSessionResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['one'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['UploadSessions']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['dropbox']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class Drive(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: Optional[CreatedAt] = None
    created_by: Optional[CreatedBy] = None
    description: Optional[Description] = None
    id: Id
    name: str = Field(
        ..., description='The name of the drive', examples=['Project Resources']
    )
    updated_at: Optional[UpdatedAt] = None
    updated_by: Optional[UpdatedBy] = None


class DriveGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: Optional[CreatedAt] = None
    created_by: Optional[CreatedBy] = None
    description: Optional[Description] = None
    display_name: Optional[str] = Field(
        None, description='The display name of the drive group', examples=['accounting']
    )
    id: Id
    name: str = Field(
        ..., description='The name of the drive group', examples=['accounting']
    )
    updated_at: Optional[UpdatedAt] = None
    updated_by: Optional[UpdatedBy] = None


class FilesSort(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    by: Optional[By] = Field(
        None,
        description='The field on which to sort the Files',
        examples=['updated_at'],
    )
    direction: Optional[SortDirection] = 'asc'


class Folder(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: Optional[CreatedAt] = None
    created_by: Optional[CreatedBy] = None
    description: Optional[str] = Field(
        None,
        description='Optional description of the folder',
        examples=['My Personal Documents'],
    )
    id: Optional[Id] = None
    name: str = Field(..., description='The name of the folder', examples=['Documents'])
    owner: Optional[Owner] = None
    parent_folders: List[LinkedFolder] = Field(
        ..., description='The parent folders of the file, starting from the root'
    )
    parent_folders_complete: Optional[bool] = Field(
        None,
        description='Whether the list of parent folder is complete. Some connectors only return the direct parent of a folder',
    )
    path: Optional[str] = Field(
        None,
        description='The full path of the folder (includes the folder name)',
        examples=['/Personal/Documents'],
    )
    size: Optional[int] = Field(
        None, description='The size of the folder in bytes', examples=[1810673]
    )
    updated_at: Optional[UpdatedAt] = None
    updated_by: Optional[UpdatedBy] = None


class GetDriveGroupResponse(BaseModel):
    data: DriveGroup
    operation: str = Field(..., description='Operation performed', examples=['one'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['DriveGroups']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetDriveGroupsResponse(BaseModel):
    data: List[DriveGroup]
    links: Optional[Links] = None
    meta: Optional[Meta] = None
    operation: str = Field(..., description='Operation performed', examples=['all'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['DriveGroups']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetDriveResponse(BaseModel):
    data: Drive
    operation: str = Field(..., description='Operation performed', examples=['one'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Drives']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetDrivesResponse(BaseModel):
    data: List[Drive]
    links: Optional[Links] = None
    meta: Optional[Meta] = None
    operation: str = Field(..., description='Operation performed', examples=['all'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Drives']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetFolderResponse(BaseModel):
    data: Folder
    operation: str = Field(..., description='Operation performed', examples=['one'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Folders']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['undefined']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetFoldersResponse(BaseModel):
    data: List[Folder]
    links: Optional[Links] = None
    meta: Optional[Meta] = None
    operation: str = Field(..., description='Operation performed', examples=['all'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Folders']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['undefined']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetUploadSessionResponse(BaseModel):
    data: UploadSession
    operation: str = Field(..., description='Operation performed', examples=['one'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['UploadSessions']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['dropbox']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class SharedLink(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: Optional[CreatedAt] = None
    download_url: Optional[str] = Field(
        None,
        description='The URL that can be used to download the file.',
        examples=['https://www.box.com/shared/static/rh935iit6ewrmw0unyul.jpeg'],
    )
    expires_at: Optional[ExpiresAt] = None
    password: Optional[str] = Field(
        None, description='Optional password for the shared link.'
    )
    password_protected: Optional[bool] = Field(
        None, description='Indicated if the shared link is password protected.'
    )
    scope: Optional[Scope] = Field(
        None, description='The scope of the shared link.', examples=['company']
    )
    target: Optional[SharedLinkTarget] = None
    target_id: str = Field(..., description='The ID of the file or folder to link.')
    updated_at: Optional[UpdatedAt] = None
    url: Optional[str] = Field(
        None,
        description='The URL that can be used to view the file.',
        examples=['https://www.box.com/s/vspke7y05sb214wjokpk'],
    )


class UnifiedFile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: Optional[CreatedAt] = None
    created_by: Optional[CreatedBy] = None
    description: Optional[str] = Field(
        None,
        description='Optional description of the file',
        examples=['A sample image'],
    )
    downloadable: Optional[bool] = Field(
        None, description='Whether the current user can download this file'
    )
    downstream_id: Optional[DownstreamId] = None
    id: Id
    mime_type: Optional[str] = Field(
        None, description='The MIME type of the file.', examples=['image/jpeg']
    )
    name: str = Field(..., description='The name of the file', examples=['sample.jpg'])
    owner: Optional[Owner] = None
    parent_folders: Optional[List[LinkedFolder]] = Field(
        None, description='The parent folders of the file, starting from the root'
    )
    parent_folders_complete: Optional[bool] = Field(
        None,
        description='Whether the list of parent folder is complete. Some connectors only return the direct parent of a file',
    )
    path: Optional[str] = Field(
        None,
        description='The full path of the file or folder (includes the file name)',
        examples=['/Documents/sample.jpg'],
    )
    size: Optional[FileSize] = None
    type: FileType
    updated_at: Optional[UpdatedAt] = None
    updated_by: Optional[UpdatedBy] = None


class GetFileResponse(BaseModel):
    data: UnifiedFile
    operation: str = Field(..., description='Operation performed', examples=['one'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['files']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetFilesResponse(BaseModel):
    data: List[UnifiedFile]
    links: Optional[Links] = None
    meta: Optional[Meta] = None
    operation: str = Field(..., description='Operation performed', examples=['all'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['files']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['google-drive']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetSharedLinkResponse(BaseModel):
    data: SharedLink
    operation: str = Field(..., description='Operation performed', examples=['one'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Shared Links']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['dropbox']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetSharedLinksResponse(BaseModel):
    data: List[SharedLink]
    links: Optional[Links] = None
    meta: Optional[Meta] = None
    operation: str = Field(..., description='Operation performed', examples=['all'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['Shared Links']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['dropbox']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )
